name: Build VYRIY F4 V4
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi python3-pip -y
          pip3 install empy==3.3.4 future lxml --break-system-packages

      - name: Configure and Build
        run: |
          # 1. Создаем пустой файл загрузчика, чтобы обмануть проверку waf
          mkdir -p Tools/bootloaders
          touch Tools/bootloaders/VYRIYF4V4_bl.bin
          
          # 2. Настраиваем плату
          ./waf configure --board OMNIBUSF4V5_5PWM_SERVO
          
          # 3. Собираем прошивку
          ./waf copter

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VYRIY_F4_V4_Firmware
          path: build/VYRIYF4V4/bin/arducopter.apj



